2023-03-21 10:26:41 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 10:27:19 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\base_location.py changed, reloading.
2023-03-21 10:27:20 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 10:28:23 [DEBUG] util.logger authenticate.py:54: employees authorization info : 1852ffd1-def9-48ec-8629-224a9c1ec877 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 10:28:23 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 10:28:23 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 10:28:23 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 10:28:23 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Anchal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 10:28:23 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 10:28:24 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Anchal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1930
2023-03-21 10:30:44 [DEBUG] util.logger authenticate.py:54: employees authorization info : 1852ffd1-def9-48ec-8629-224a9c1ec877 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 10:30:44 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 10:30:44 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 10:30:44 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 10:30:44 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Puthenkulam%2C+691302&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 10:30:44 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 10:30:44 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Puthenkulam%2C+691302&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1750
2023-03-21 13:32:23 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 13:32:50 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-21 13:32:50 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-21 13:33:27 [DEBUG] util.logger authenticate.py:54: employees authorization info : 37b5c6a5-9d62-4635-a30e-5fbe582dbee7 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 13:33:27 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:33:27 [ERROR] util.logger basic_info.py:71: Failed to update employee basic info : 554ab970-d1b7-46e2-8b72-f102463eb97f - Profile name is already used
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\basic_info.py", line 32, in index
    raise Exception("Profile name is already used")
Exception: Profile name is already used

2023-03-21 13:33:27 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/basic/
2023-03-21 13:33:35 [DEBUG] util.logger authenticate.py:54: employees authorization info : 37b5c6a5-9d62-4635-a30e-5fbe582dbee7 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 13:33:35 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:33:35 [ERROR] util.logger basic_info.py:71: Failed to update employee basic info : 554ab970-d1b7-46e2-8b72-f102463eb97f - This Email ID is already used
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\basic_info.py", line 45, in index
    raise Exception("This Email ID is already used")
Exception: This Email ID is already used

2023-03-21 13:33:35 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/basic/
2023-03-21 13:33:44 [DEBUG] util.logger authenticate.py:54: employees authorization info : 37b5c6a5-9d62-4635-a30e-5fbe582dbee7 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 13:33:45 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:33:45 [ERROR] util.logger basic_info.py:71: Failed to update employee basic info : 554ab970-d1b7-46e2-8b72-f102463eb97f - "to" argument must be a list or tuple
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\profile\update\basic_info.py", line 47, in index
    send_email("email_verification_template", {"employee_id":employee_id}, email_id)
  File "C:\aravind\lens35\util\email_util.py", line 20, in send_email
    msg = EmailMultiAlternatives(subject, text_message, from_email, recipient_list)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\mail\message.py", line 459, in __init__
    super().__init__(
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\mail\message.py", line 216, in __init__
    raise TypeError('"to" argument must be a list or tuple')
TypeError: "to" argument must be a list or tuple

2023-03-21 13:33:45 [WARNING] django.request log.py:241: Bad Request: /employees/apis/profile/update/basic/
2023-03-21 13:34:10 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\employees\apis\profile\update\basic_info.py changed, reloading.
2023-03-21 13:34:10 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 13:34:12 [DEBUG] util.logger authenticate.py:54: employees authorization info : 37b5c6a5-9d62-4635-a30e-5fbe582dbee7 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 13:34:12 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:34:15 [DEBUG] util.logger authenticate.py:54: employees authorization info : 37b5c6a5-9d62-4635-a30e-5fbe582dbee7 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 13:34:15 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:34:39 [DEBUG] util.logger authenticate.py:54: employees authorization info : 37b5c6a5-9d62-4635-a30e-5fbe582dbee7 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 13:34:39 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:34:49 [DEBUG] util.logger authenticate.py:54: employees authorization info : 37b5c6a5-9d62-4635-a30e-5fbe582dbee7 | Identifier : 554ab970-d1b7-46e2-8b72-f102463eb97f | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a424
2023-03-21 13:34:49 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:34:49 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:34:49 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:34:49 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Puthenkulam%2C+691302&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:34:49 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:34:49 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Puthenkulam%2C+691302&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1750
2023-03-21 13:36:07 [DEBUG] util.logger generate_token_api.py:81: Creating new Employee record
2023-03-21 13:36:49 [DEBUG] util.logger authenticate.py:54: employees authorization info : 4849fcc9-1978-4b73-8a43-74b46c35c98f | Identifier : ffd3085b-f381-4c30-a367-e33fff4ca463 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a422
2023-03-21 13:36:49 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:36:59 [DEBUG] util.logger authenticate.py:54: employees authorization info : 4849fcc9-1978-4b73-8a43-74b46c35c98f | Identifier : ffd3085b-f381-4c30-a367-e33fff4ca463 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a422
2023-03-21 13:36:59 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:37:19 [DEBUG] util.logger authenticate.py:54: employees authorization info : 4849fcc9-1978-4b73-8a43-74b46c35c98f | Identifier : ffd3085b-f381-4c30-a367-e33fff4ca463 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a422
2023-03-21 13:37:19 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:37:19 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:37:19 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:37:19 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Mayyanad%2C+691303&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:37:19 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:37:20 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Mayyanad%2C+691303&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1764
2023-03-21 13:38:09 [WARNING] django.request log.py:241: Unauthorized: /employees/apis/generate/token/
2023-03-21 13:38:18 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-21 13:38:18 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-21 13:38:23 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-21 13:38:23 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-21 13:38:39 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\employees\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-21 13:38:39 [WARNING] django.request log.py:241: Bad Request: /employees/apis/generate/token/
2023-03-21 13:38:46 [DEBUG] util.logger generate_token_api.py:81: Creating new Employee record
2023-03-21 13:39:14 [DEBUG] util.logger authenticate.py:54: employees authorization info : 2dc05d1e-601b-4bb5-8ce3-8c576f665c4c | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:39:14 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:39:32 [DEBUG] util.logger authenticate.py:54: employees authorization info : 2dc05d1e-601b-4bb5-8ce3-8c576f665c4c | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:39:32 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:39:57 [DEBUG] util.logger authenticate.py:54: employees authorization info : 2dc05d1e-601b-4bb5-8ce3-8c576f665c4c | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:39:57 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:39:57 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:39:57 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:39:57 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Anchal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:39:57 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:39:58 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Anchal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1930
2023-03-21 13:42:38 [ERROR] util.logger generate_token_api.py:47: Failed : Invalid OTP
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\customers\apis\authenticate\generate_token_api.py", line 21, in index
    otp = validate_and_format_otp(data.get("otp", None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\aravind\lens35\util\regex.py", line 23, in validate_and_format_otp
    raise Exception("Invalid OTP")
Exception: Invalid OTP

2023-03-21 13:42:38 [WARNING] django.request log.py:241: Bad Request: /customers/apis/generate/token/
2023-03-21 13:43:34 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:43:34 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:44:03 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:44:03 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:44:03 [ERROR] util.logger handle_booking.py:190: Failed to handle the booking request None
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\customers\handle_booking.py", line 74, in index
    raise Exception("Event date must be on or after today")
Exception: Event date must be on or after today

2023-03-21 13:44:03 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/customers/booking/
2023-03-21 13:44:51 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:44:51 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:44:51 [ERROR] util.logger handle_booking.py:190: Failed to handle the booking request None
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\customers\handle_booking.py", line 155, in index
    address = "{}, {}".format(booking.event_city, booking.pincode)
                                                  ^^^^^^^^^^^^^^^
AttributeError: 'Bookings' object has no attribute 'pincode'

2023-03-21 13:44:51 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/customers/booking/
2023-03-21 13:45:10 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\customers\handle_booking.py changed, reloading.
2023-03-21 13:45:11 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 13:45:13 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:45:13 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:45:13 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:45:13 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:45:13 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Kottukkal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:45:13 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:45:13 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Kottukkal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1758
2023-03-21 13:45:13 [ERROR] util.logger handle_booking.py:190: Failed to handle the booking request None
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column "event_latitude" of relation "bookings" does not exist
LINE 1: ...vent_postal_code", "event_city", "event_address", "event_lat...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\customers\handle_booking.py", line 175, in index
    booking.save()
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column "event_latitude" of relation "bookings" does not exist
LINE 1: ...vent_postal_code", "event_city", "event_address", "event_lat...
                                                             ^


2023-03-21 13:45:13 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/customers/booking/
2023-03-21 13:45:33 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 13:45:35 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:45:35 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:45:35 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:45:35 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:45:35 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Kottukkal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:45:35 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:45:35 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Kottukkal%2C+691306&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1758
2023-03-21 13:46:51 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:46:51 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:48:38 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:48:38 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:48:38 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:48:38 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:48:38 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Pullichira%2C+691304&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:48:38 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:48:38 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Pullichira%2C+691304&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1834
2023-03-21 13:49:12 [DEBUG] util.logger authenticate.py:54: customers authorization info : 3dc76335-2d21-4a0b-bead-6d30d61e8da8 | Identifier : be150b1e-7686-4e5a-bf62-e424f6a181b5 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:49:13 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:50:20 [WARNING] django.request log.py:241: Unauthorized: /customers/apis/generate/token/
2023-03-21 13:50:30 [WARNING] django.request log.py:241: Unauthorized: /customers/apis/generate/token/
2023-03-21 13:50:40 [DEBUG] util.logger generate_token_api.py:81: Creating new Employee record
2023-03-21 13:51:12 [DEBUG] util.logger authenticate.py:54: customers authorization info : 784f6c28-93be-4791-bee9-fce44420962c | Identifier : 9a64965b-26ee-4142-b757-b023f004b917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:51:12 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:52:52 [DEBUG] util.logger authenticate.py:54: customers authorization info : 784f6c28-93be-4791-bee9-fce44420962c | Identifier : 9a64965b-26ee-4142-b757-b023f004b917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:52:52 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:52:52 [ERROR] util.logger handle_booking.py:190: Failed to handle the booking request None
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\customers\handle_booking.py", line 104, in index
    raise Exception("Minimum Booking must be for 2 Hours")
Exception: Minimum Booking must be for 2 Hours

2023-03-21 13:52:52 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/customers/booking/
2023-03-21 13:53:04 [DEBUG] util.logger authenticate.py:54: customers authorization info : 784f6c28-93be-4791-bee9-fce44420962c | Identifier : 9a64965b-26ee-4142-b757-b023f004b917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:53:04 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:53:04 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:53:04 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:53:04 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=HAL%2C+560017&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:53:04 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:53:04 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=HAL%2C+560017&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 2539
2023-03-21 13:54:13 [DEBUG] util.logger authenticate.py:54: customers authorization info : 784f6c28-93be-4791-bee9-fce44420962c | Identifier : 9a64965b-26ee-4142-b757-b023f004b917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:54:13 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:56:10 [DEBUG] util.logger authenticate.py:54: customers authorization info : 784f6c28-93be-4791-bee9-fce44420962c | Identifier : 9a64965b-26ee-4142-b757-b023f004b917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:56:10 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 13:56:10 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:56:10 [DEBUG] urllib3.util.retry retry.py:351: Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
2023-03-21 13:56:10 [DEBUG] geopy google.py:274: GoogleV3.geocode: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=Kakkotumoola%2C+691303&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0
2023-03-21 13:56:10 [DEBUG] urllib3.connectionpool connectionpool.py:1003: Starting new HTTPS connection (1): maps.googleapis.com:443
2023-03-21 13:56:10 [DEBUG] urllib3.connectionpool connectionpool.py:456: https://maps.googleapis.com:443 "GET /maps/api/geocode/json?sensor=false&address=Kakkotumoola%2C+691303&key=AIzaSyD2B8eQw12B5vd_jore80-hbquUAu1WxO0 HTTP/1.1" 200 1828
2023-03-21 13:56:20 [DEBUG] util.logger authenticate.py:54: customers authorization info : 784f6c28-93be-4791-bee9-fce44420962c | Identifier : 9a64965b-26ee-4142-b757-b023f004b917 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 13:56:20 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:00:20 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\api_urls.py changed, reloading.
2023-03-21 14:00:21 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:05:00 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:05:00 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:05:03 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:05:03 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:05:18 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:05:19 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:05:26 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\api_urls.py changed, reloading.
2023-03-21 14:05:27 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:07:31 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:07:31 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:08:05 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:08:05 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:08:05 [ERROR] util.logger list_bookings.py:67: Failed to fetch the bookings for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\list_bookings.py", line 19, in index
    event_date = timezone.now().date() if (event_date == None or event_date == "") else datetime.fromisoformat(event_date).date()
                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: '23-03-2023'

2023-03-21 14:08:05 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/list/
2023-03-21 14:08:40 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:08:40 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:10:17 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:10:18 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:10:19 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:10:19 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:10:22 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:10:22 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:10:36 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:10:36 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:10:38 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:10:39 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:11:21 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:11:22 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:11:23 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:11:23 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:11:49 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:11:50 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:11:51 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:11:51 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:12:04 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:12:04 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:12:06 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:12:06 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:15:00 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:15:01 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:16:13 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:16:13 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:16:13 [ERROR] util.logger list_bookings.py:73: Failed to fetch the bookings for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\list_bookings.py", line 68, in index
    "services": list(booking.services.values_list('service', flat=True).distinct())
                     ^^^^^^^^^^^^^^^^
AttributeError: 'Bookings' object has no attribute 'services'

2023-03-21 14:16:13 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/list/
2023-03-21 14:18:20 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\customers\add_services.py changed, reloading.
2023-03-21 14:18:20 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:18:48 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\customers\add_services.py changed, reloading.
2023-03-21 14:18:48 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:21:14 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\models\bookings.py changed, reloading.
2023-03-21 14:21:14 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:21:52 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:22:42 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:22:50 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:22:50 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:22:50 [ERROR] util.logger list_bookings.py:73: Failed to fetch the bookings for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\list_bookings.py", line 68, in index
    "services": list(booking.services.values_list('service', flat=True).distinct())
                     ^^^^^^^^^^^^^^^^
AttributeError: 'Bookings' object has no attribute 'services'

2023-03-21 14:22:50 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/list/
2023-03-21 14:28:16 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:28:16 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:28:19 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:28:19 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:28:28 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:28:31 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:28:31 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:28:31 [ERROR] util.logger list_bookings.py:75: Failed to fetch the bookings for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 2142, in add_fields
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1808, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'service_code' into field. Choices are: booking, booking_id, created_time, employee, employee_id, employeepreference, id, lifecycle, retired, service, service_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\list_bookings.py", line 63, in index
    services = Services.objects.filter(booking = booking, employee = None).values_list('service_code', flat=True).distinct()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1330, in values_list
    clone = self._values(*_fields, **expressions)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1293, in _values
    clone.query.set_values(fields)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 2437, in set_values
    self.add_fields(field_names, True)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\query.py", line 2175, in add_fields
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'service_code' into field. Choices are: booking, booking_id, created_time, employee, employee_id, employeepreference, id, lifecycle, retired, service, service_id

2023-03-21 14:28:31 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/list/
2023-03-21 14:28:42 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:28:42 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:28:44 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:28:44 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:31:21 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:31:21 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:31:23 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:31:23 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:31:54 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:31:55 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:32:48 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:32:48 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:34:17 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:34:17 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:34:20 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:34:20 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:35:27 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:35:27 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:35:41 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:35:41 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:36:12 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:36:12 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:36:14 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:36:14 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:37:31 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:37:31 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:37:40 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:37:40 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:37:47 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:37:47 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:50:13 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\lens35\constanst.py changed, reloading.
2023-03-21 14:50:14 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:51:40 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:51:41 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:51:45 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:51:45 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:51:52 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:51:52 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:51:57 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:51:57 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:52:05 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:52:05 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:52:09 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:52:09 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:52:57 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:52:57 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:53:02 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:53:02 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:53:35 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:53:36 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:53:46 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:53:46 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:54:28 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:54:28 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:54:30 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:54:30 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:54:56 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:54:56 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:55:59 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:55:59 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:56:20 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:56:20 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:56:23 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:56:23 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:56:29 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:56:29 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:56:32 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 14:56:32 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 14:56:34 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:56:34 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 14:56:38 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 14:56:38 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 15:00:21 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 15:00:21 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 15:00:28 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 15:00:28 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 15:20:09 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\api_urls.py changed, reloading.
2023-03-21 15:20:09 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 15:20:32 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 15:20:32 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 15:21:06 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\fetch_booking_info.py changed, reloading.
2023-03-21 15:21:06 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 15:21:09 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 15:21:09 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 15:23:41 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 15:23:41 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 15:23:52 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\list_bookings.py changed, reloading.
2023-03-21 15:23:53 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:06:39 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\fetch_booking_info.py changed, reloading.
2023-03-21 16:06:40 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:26:37 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\api_urls.py changed, reloading.
2023-03-21 16:26:37 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:30:38 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:30:38 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:30:38 [WARNING] django.request log.py:241: Method Not Allowed: /bookings/apis/employees/bookings/accept/
2023-03-21 16:30:49 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:30:50 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:30:54 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:30:54 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:30:54 [ERROR] django.request log.py:241: Internal Server Error: /bookings/apis/employees/bookings/accept/
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: index() missing 1 required positional argument: 'booking_id'
2023-03-21 16:31:17 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:31:17 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:31:17 [ERROR] django.request log.py:241: Internal Server Error: /bookings/apis/employees/bookings/accept/
Traceback (most recent call last):
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: index() missing 1 required positional argument: 'booking_id'
2023-03-21 16:31:41 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:31:41 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:31:43 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:31:43 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:38:01 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:38:01 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:38:04 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:38:04 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:38:04 [ERROR] util.logger accept_booking.py:37: Failed to fetch the bookings for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\accept_booking.py", line 33, in index
    raise Exception("Employee is not registered to accept {} bookings".format(service.service))
Exception: Employee is not registered to accept photography bookings

2023-03-21 16:38:04 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/accept/
2023-03-21 16:38:25 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:38:25 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:38:52 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:38:52 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:38:54 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:38:55 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:40:11 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:40:11 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:40:58 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:40:59 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:41:18 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:41:18 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:41:20 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:41:20 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:41:26 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:41:26 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:42:19 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:42:20 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:42:22 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:42:22 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:42:22 [ERROR] util.logger accept_booking.py:44: Failed to fetch the bookings for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\accept_booking.py", line 26, in index
    raise Exception("Invalid service id found in the request")
Exception: Invalid service id found in the request

2023-03-21 16:42:22 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/accept/
2023-03-21 16:42:29 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:42:29 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:50:59 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:50:59 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:51:07 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\apis\employees\accept_booking.py changed, reloading.
2023-03-21 16:51:07 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:51:20 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:51:20 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:51:20 [WARNING] django.request log.py:241: Not Found: /bookings/apis/employees/bookings/remove/
2023-03-21 16:51:51 [INFO] django.utils.autoreload autoreload.py:266: C:\aravind\Lens35\apps\bookings\api_urls.py changed, reloading.
2023-03-21 16:51:51 [INFO] django.utils.autoreload autoreload.py:677: Watching for file changes with StatReloader
2023-03-21 16:51:54 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:51:54 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:51:54 [ERROR] util.logger remove_booking.py:35: Failed to remove booking/service for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\remove_booking.py", line 21, in index
    service_id_list.append(UUID(sid))
                           ^^^^^^^^^
  File "C:\Users\apillai\AppData\Local\Programs\Python\Python311\Lib\uuid.py", line 179, in __init__
    int = int_(hex, 16)
          ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: '90834251bd8c4451ab9c0018107cadcs'

2023-03-21 16:51:54 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/remove/
2023-03-21 16:52:08 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:52:08 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
2023-03-21 16:52:08 [ERROR] util.logger remove_booking.py:35: Failed to remove booking/service for employee 976b4889-4fd6-4ccc-a7ce-f540a5e89f48
Traceback (most recent call last):
  File "C:\aravind\lens35\apps\bookings\apis\employees\remove_booking.py", line 25, in index
    raise Exception("Invalid service id found in the request")
Exception: Invalid service id found in the request

2023-03-21 16:52:08 [WARNING] django.request log.py:241: Bad Request: /bookings/apis/employees/bookings/remove/
2023-03-21 16:52:15 [DEBUG] util.logger authenticate.py:54: employees authorization info : f98b27b4-f976-4051-b3b9-90326765ae72 | Identifier : 976b4889-4fd6-4ccc-a7ce-f540a5e89f48 | Device ID : b30b71c1-e473-4837-b4a7-98280bc4a423
2023-03-21 16:52:15 [DEBUG] util.logger authenticate.py:67: KeepActive is true for this Token.
